### ISSUE TITLE
Item name not displayed when selecting item in rolls

### ISSUE THREAD

**Issue by Sensoria1** [DrOgres/tftloop#10]
It seems that when selecting an item other that your Iconic Item in the dice roll dialogue, the item name isn't displayed.
![Item name not displayed](https://user-images.githubusercontent.com/79567005/109382293-e6ca7480-78df-11eb-9510-e12aa2314f1b.jpg)

**Comment by DrOgres** [comment]
This is fixed in 0.9.1 will be released tomorrow pending a couple other small things I want to do.

**Comment by DrOgres** [comment]
0.9.1 released and fixed this
