### ISSUE TITLE
Starter Set requires 1.0.6?

### ISSUE THREAD

**Issue by profdresser** [DrOgres/tftloop#18]
I recently purchased the TftL Starter Set. It aborted the import, however, because it stated that I needed v1.0.6 of the game system. Is there an updated version planned soon?

**Comment by drspin** [comment]
fwiw, I also ran into the same issue with a recently purchased core TftL foundry vtt module

**Comment by DrOgres** [comment]
I pushed an update to align this.  Sorry for the inconvenience!  it should
work now

-David

**Comment by drspin** [comment]
Works for me! Thank you very much!
