### ISSUE TITLE
Can't drag and drop abilities in macro bar

### ISSUE THREAD

**Issue by ICronyI** [DrOgres/tftloop#31]
Hello :)
It would be nice to be able to drop attribute and abilities rolls into the macro bar, for easy access. I know it can be done as i've seen other systems allowing it 
Thank you for your consideration

**Comment by DrOgres** [comment]
started work on this will be in 2.0.4

**Comment by DrOgres** [comment]
added to 2.0.4 released and ready to go let me know if you run into any issues
