### ISSUE TITLE
Blank actor and item sheets

### ISSUE THREAD

**Issue by saeldion** [DrOgres/tftloop#35]
I just installed the system for the first time on my foundry set up. Whenever I create an Actor or Item all I get is a blank window.
Am I missing something in the setup? Any required modules?

![image](https://user-images.githubusercontent.com/2678144/203600172-43ec7bc0-5f9d-4c1d-a1a7-04940e43eaed.png)

I'm running Foundry 9.280 and TftL 1.2.7

**Comment by DrOgres** [comment]
can you open the dev console and see if there are any errors in the log. 

also helpful to know:
What browser are you using, any other modules active and the versions of those.

**Comment by saeldion** [comment]
Running on Chrome 107 and no errors in the developer console. Only a warning about a missing font.

When I inspect the sheet the entier sheet consists of these few lines:

```
<section class="window-content">
    <form class="actor-sheet editable" autocomplete="off">
        <header class="sheet-header">
            <img src="icons/svg/mystery-man.svg" data-edit="img" title="Agnes" height="64" width="64">
            <h1 class="charname"><input name="name" type="text" value="Agnes" placeholder=" Name"></h1>
        </header>

        <section class="items">
            <h3>Owned Items</h3>
            <ol class="actor-items">
            </ol>
        </section>
    </form>
</section>
```

**Comment by DrOgres** [comment]
try deleting it and re-downloading. I updated the 1.2.7 zip file so it should have all the correct files in it now let me know if that fixes your issue

**Comment by saeldion** [comment]
Perfect! Now it seems to be working!

**Comment by DrOgres** [comment]
woot!  thanks for the report.
