### ISSUE TITLE
[BUG] Can't duplicate actors in V10

### ISSUE THREAD

**Issue by ICronyI** [DrOgres/tftloop#37]
When updated to V10, once i try to right click and duplicate an actor, nothing happens. I opened the console, and this is what i saw in it: 

![image](https://user-images.githubusercontent.com/108086957/212800241-fc5fd5e5-f271-4a8d-a817-097446a5fec3.png)

Anything i can do to fix it? 
Thanks in advance!

**Comment by DrOgres** [comment]
this is fixed in the next release thanks for the bug report!

**Comment by DrOgres** [comment]
fixed in 2.0.3 thanks again
