### ISSUE TITLE
Can't seem to be able to make hidden rolls from sheet

### ISSUE THREAD

**Issue by ICronyI** [DrOgres/tftloop#39]
as the title says, it seems like you can't do hidden rolls if you do them from the sheet
A little "hidden roll" box to tick on the sheet that allows every roll to be rolled as hidden from everyone but the GM would be great!

**Comment by DrOgres** [comment]
this is a bug, Trying to track it down but will take some time as the roll mode is being set correctly as far as I can determine.  will keep poking at it.

**Comment by DrOgres** [comment]
Fixed in 2.0.5
