### ISSUE TITLE
Initiative Dice Button in Turn Order

### ISSUE THREAD

**Issue by Tarubain** [DrOgres/tftloop#40]
I know that Initiative is not a big deal in Tales from the Loop but we are using some sort of Initiative for final boss battles (not using the big trouble rule). At the moment the system throws an JS error on pushing the initiative dice button in the turn tracker.

I was wondering if there is a way to get this button working...

@DrOgres Any hints on how this can be done?

**Comment by DrOgres** [comment]
fixed in 2.0.6

**Comment by Tarubain** [comment]
> fixed in 2.0.6

Thanks! :)
