### ISSUE TITLE
Weird dice rolls with negative Dice Pool

### ISSUE THREAD

**Issue by Tarubain** [DrOgres/tftloop#41]
We had an interesting case today. This character (screenshot) has only 1 in Body and 0 in Sneak. The character had 2 conditions at this point. Another character rolled Lead on him with a success, whereupon 2 bonus dice are granted.

**Two things now happened:**

1. without entering bonus dice in the dice dialog, the dice pool shows a 0. This can't be true, because according to the rulebook, 1 die is always granted unless you are Broken. However system still rolls the 1d6 correctly. So only the display in the dice dialog is wrong. It is not that bad. :)

2. now it gets strange: after adding the 2 bonus dice (by Lead) the system rolls 2d6. It should actually still only roll 1d6. (1 body - 2 conditions + 2 bonus dices = 1d6).

Odd. :)

![Bildschirm­foto 2023-04-07 um 22 55 46](https://user-images.githubusercontent.com/119525639/230695609-f019bc85-a09a-48a6-a9ab-20b1418799d2.png)

**Comment by DrOgres** [comment]
thanks  for the report.  I'll dig in and get a fix asap

**Comment by DrOgres** [comment]
fixed in 2.0.7 thanks!

**Comment by Tarubain** [comment]
Great job, thx. Will have a look into your changes for my fork as well. 😊
