### ISSUE TITLE
Dice so nice hidden rolls from sheet

### ISSUE THREAD

**Issue by ICronyI** [DrOgres/tftloop#43]
When rolling a dice from a skill on the sheet, even if the roll is set as a private roll the 3d dices will show up on screen (the results will be in private in the chat as should be, but the players actually do see the dices being rolled)
It does not happen if you roll a private d6 dice, it's only from the sheet

**Comment by DrOgres** [comment]
must be a bug with the interaction of the system and dice so nice. I'll investigate

thanks

**Comment by DrOgres** [comment]
fixed in 2.0.9
