### ISSUE TITLE
Relationship Data Field won't save any strings in charactersheet of Things from the Flood

### ISSUE THREAD

**Issue by Tarubain** [DrOgres/tftloop#44]
Hey!

The second relationship data field (the big one right) does not save any strings in the character sheet of Things from the Flood.

![image](https://github.com/DrOgres/tftloop/assets/119525639/537ac3df-048c-4c58-8f71-6cba16d827aa)

No big deal, just reporting. :)

**Comment by DrOgres** [comment]
fixed in 2.0.10 thanks!
