### ISSUE TITLE
Dragging a Relationship/Item, without it leaving the character sheet, permanently deletes it. 

### ISSUE THREAD

**Issue by LucifurMacomb** [DrOgres/tftloop#52]
When creating a Relationship or an Item (on both the Kid & Teen sheets), it is possible to click and drag these items - when doing so, if you drag the item up or down and release: the Item/Relationship will permanently disappear from the character sheet. 

This issue is does not affect Scars, oddly.  

As far as I can tell, to recreate the issue, you would just make a new Relationship/Item and click+drag it. 

Footage below. 

https://github.com/DrOgres/tftloop/assets/87908174/c8c27e59-2540-4d81-a232-397db0c90274

**Comment by LucifurMacomb** [comment]
I understand in last update changes to drag and drop were made and the purpose behind it, but a few of my players have since accidentally deleted contacts and items when trying to edit text fields - attempting to drag the cursor over text and instead dragging [items] without somewhere to deposit the item. It would be nice to see this fixed in a future update; thank you!

**Comment by DrOgres** [comment]
thank you for the report. I'll get a fix out asap

**Comment by DrOgres** [comment]
this is fixed in v3.0.0
