### ISSUE TITLE
XP toggles don't activate

### ISSUE THREAD

**Issue by AnlashokNa** [DrOgres/tftloop#53]
In Foundry v12, the XP toggles do not activate. Other toggles such as for Shame and Scar do activate properly.

**Comment by bithir** [comment]
Code fix

Change
`    actor.update({ "data.exp": newCount });`
to
`    actor.update({ "system.exp": newCount });`

In https://github.com/DrOgres/tftloop/blob/b0d2ac61d3dfe0e088daed8b9e25f93419c42f97/module/actor/sheet.js#L657

**Comment by DrOgres** [comment]
fixed in 3.0.1 thanks @bithir  for the assist!
